import fs from "node:fs/promises";
import path from "node:path";
import type { WikiLogEntryT, WikiLogKindT, WikiStateT } from "../schema/wiki.js";
import { nowIso, shortId } from "../state/ids.js";
import { CLI_NAME } from "../branding.js";

export interface WikiFsPaths {
  wikiDir: string;
  wikiRawDir: string;
  wikiPagesDir: string;
  wikiIndexFile: string;
  wikiLogFile: string;
  wikiSchemaFile: string;
}

const SCHEMA_TEMPLATE = `# wiki/schema.md

This wiki is the agent-managed knowledge surface for this project. The harness state owns
the metadata; this directory is the readable mirror.

## Layout

- raw/ - original sources the wiki was synthesised from. Read-only by convention.
- pages/<page_id>.md - one page per knowledge unit. Body only; metadata lives in state.json.
- index.md - generated overview. Do not edit by hand.
- log.md - append-only narrative. Do not edit by hand.

## Page conventions

- Pages have stable ids (slug). Renames go through '${CLI_NAME} wiki page upsert' so links stay valid.
- Each page lists 1+ source ids. A page with no sources is an orphan and 'wiki lint' will flag it.
- Pages reference each other with [[page_id]] tokens; lint resolves them.

## Authoring

- The agent calls '${CLI_NAME} wiki page upsert' to create or update a page.
- Pages should be terse. Prefer linking to raw/ over duplicating it.
`;

export async function ensureWikiDirs(paths: WikiFsPaths): Promise<void> {
  await fs.mkdir(paths.wikiDir, { recursive: true });
  await fs.mkdir(paths.wikiRawDir, { recursive: true });
  await fs.mkdir(paths.wikiPagesDir, { recursive: true });
}

export async function writeWikiSchemaIfMissing(paths: WikiFsPaths): Promise<boolean> {
  try {
    await fs.access(paths.wikiSchemaFile);
    return false;
  } catch {
    await fs.writeFile(paths.wikiSchemaFile, SCHEMA_TEMPLATE, "utf8");
    return true;
  }
}

export async function writeWikiIndex(
  paths: WikiFsPaths,
  state: { wiki: WikiStateT },
): Promise<void> {
  const wiki = state.wiki;
  const lines: string[] = [];
  lines.push("# wiki index");
  lines.push("");
  lines.push(`Generated by ${CLI_NAME}. Do not edit by hand.`);
  lines.push("");
  if (!wiki.initialized) {
    lines.push("Wiki not initialized.");
  } else {
    lines.push(`- pages: ${Object.keys(wiki.pages).length}`);
    lines.push(`- sources: ${Object.keys(wiki.sources).length}`);
    lines.push(`- log entries: ${wiki.log.length}`);
    lines.push("");
    const pages = Object.values(wiki.pages).sort((a, b) =>
      b.updated_at.localeCompare(a.updated_at),
    );
    if (pages.length > 0) {
      lines.push("## pages (most recent first)");
      lines.push("");
      for (const p of pages) {
        const rel = path.relative(paths.wikiDir, path.join(paths.wikiDir, p.body_path));
        lines.push(`- [${p.title}](${rel.replace(/\\/g, "/")}) - id: ${p.id}, sources: ${p.source_ids.length}, updated: ${p.updated_at}`);
      }
      lines.push("");
    }
    const sources = Object.values(wiki.sources).sort((a, b) =>
      b.added_at.localeCompare(a.added_at),
    );
    if (sources.length > 0) {
      lines.push("## sources");
      lines.push("");
      for (const s of sources) {
        lines.push(`- ${s.title} (${s.id}) - raw/${s.raw_path}`);
      }
      lines.push("");
    }
  }
  await fs.writeFile(paths.wikiIndexFile, lines.join("\n"), "utf8");
}

export async function appendWikiLog(
  paths: WikiFsPaths,
  entry: WikiLogEntryT,
): Promise<void> {
  let preface = "";
  try {
    await fs.access(paths.wikiLogFile);
  } catch {
    preface = `# wiki log\n\nAppend-only. Do not edit by hand.\n\n`;
  }
  const line = `- ${entry.at} ${entry.kind}${entry.ref ? ` ref=${entry.ref}` : ""}${entry.note ? ` - ${entry.note.replace(/\n/g, " ")}` : ""}\n`;
  await fs.appendFile(paths.wikiLogFile, preface + line, "utf8");
}

export function makeWikiLogEntry(
  kind: WikiLogKindT,
  ref?: string,
  note?: string,
): WikiLogEntryT {
  return {
    id: shortId("wlg"),
    kind,
    ref,
    note,
    at: nowIso(),
  };
}
