import { z } from "zod";
import { IsoDateTime, SlugId } from "./common.js";

export const EventKind = z.enum([
  "init",
  "goal.created",
  "goal.updated",
  "goal.activated",
  "goal.blocked",
  "ticket.created",
  "ticket.started",
  "ticket.blocked",
  "ticket.submitted",
  "ticket.done",
  "phase.created",
  "phase.activated",
  "phase.completed",
  "phase.blocked",
  "task.created",
  "task.activated",
  "task.completed",
  "task.blocked",
  "checkpoint.recorded",
  "smoke.recorded",
  "session.started",
  "session.snapshotted",
  "wiki.created",
  "wiki.source.added",
  "wiki.page.created",
  "wiki.page.updated",
  "wiki.checkpoint",
  "wiki.linted",
  "review.opened",
  "review.verdict.recorded",
  "review.finding.resolved",
  "review.fix_loop.started",
  "review.round.recorded",
  "review.closed",
  "ritual.recorded",
  "artifact.registered",
  "goal.worktree.created",
  "goal.scaffolded",
  "commit.recorded",
  "goal.worktree.finished",
]);
export type EventKindT = z.infer<typeof EventKind>;

export const Event = z.object({
  id: SlugId,
  kind: EventKind,
  at: IsoDateTime,
  goal_id: SlugId.optional(),
  phase_id: SlugId.optional(),
  task_id: SlugId.optional(),
  ticket_id: SlugId.optional(),
  checkpoint_id: SlugId.optional(),
  smoke_id: SlugId.optional(),
  session_id: SlugId.optional(),
  payload: z.record(z.unknown()).optional(),
});
export type EventT = z.infer<typeof Event>;
